# Generated by Django 3.0 on 2019-12-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecoursesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
